name: Deploy Twitch Frontend Image

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 取得專案原始碼
      - name: Checkout repository
        uses: actions/checkout@v3

      # 登入 Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # Build Docker image
      - name: Build Docker Image
        run: |
          docker build -t csdsdasdcwcwadx/twitch-frontend:latest .

      # Push Docker image to Docker Hub
      - name: Push Docker Image
        run: |
          docker push csdsdasdcwcwadx/twitch-frontend:latest

      # SSH deploy to Vultr
      - name: Deploy to Vultr via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /root/twitch
            docker-compose pull frontend
            docker-compose up -d frontend
            docker image prune -f
